EnableDefaultLinters: true
exclude:
  - "**/vendor/**/*"
  - "**/vendor/**/.*"
  - "**/rails/templates/**"
  - "**/lib/rails/templates/**"
  - "bin/**"
  - "db/**/*"
  - "spec/**/*"
  - "config/**/*"
  - "node_modules/**/*"
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
